# Task 1: Load and Inspect the Data

In [3]:
import pandas as pd
import numpy as np

data = {
    'transaction_id': range(1, 21),
    'date': pd.date_range('2024-10-01', periods=20, freq='D'),
    'region': ['North', 'South', 'East', 'West', None, 'North', 'South', None, 'East', 'West',
               'North', 'South', 'East', 'West', 'North', None, 'East', 'West', 'North', 'South'],
    'product_category': ['Electronics', 'Clothing', None, 'Books', 'Electronics', 'Home',
                         'Clothing', 'Books', 'Electronics', None, 'Home', 'Clothing',
                         'Books', 'Electronics', 'Home', 'Clothing', 'Books', 'Electronics',
                         'Home', 'Clothing'],
    'sales_amount': [1200, 450, 890, None, 1500, 670, None, 340, 2100, 780,
                     560, None, 420, 1800, 920, 510, 380, None, 1100, 640],
    'quantity': [2, 5, 3, 1, None, 4, 2, 3, 1, 5,
                 3, 2, None, 1, 4, 3, 2, 1, None, 4],
    'customer_age': [25, 34, None, 45, 29, None, 38, 52, 27, 41,
                     33, None, 48, 26, 35, 42, None, 31, 39, 44],
    'payment_method': ['Credit Card', 'UPI', 'Cash', 'Debit Card', 'Credit Card',
                       'UPI', 'Cash', None, 'Credit Card', 'UPI', 'Debit Card',
                       'Cash', 'Credit Card', None, 'UPI', 'Cash', 'Debit Card',
                       'Credit Card', 'UPI', None]
}

df = pd.DataFrame(data)
df.info()
df.isna().sum()
df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   transaction_id    20 non-null     int64
 1   date              20 non-null     datetime64[ns]
 2   region            17 non-null     object
 3   product_category  18 non-null     object
 4   sales_amount      16 non-null     float64
 5   quantity          17 non-null     float64
 6   customer_age      16 non-null     float64
 7   payment_method    17 non-null     object
dtypes: datetime64[ns](1), float64(3), int64(1), object(3)
memory usage: 1.4+ KB

,transaction_id,date,region,product_category,sales_amount,quantity,customer_age,payment_method
0,1,2024-10-01,North,Electronics,1200.0,2.0,25.0,Credit Card
1,2,2024-10-02,South,Clothing,450.0,5.0,34.0,UPI
2,3,2024-10-03,East,None,890.0,3.0,NaN,Cash
3,4,2024-10-04,West,Books,NaN,1.0,45.0,Debit Card
4,5,2024-10-05,None,Electronics,1500.0,NaN,29.0,Credit Card
5,6,2024-10-06,North,Home,670.0,4.0,NaN,UPI
6,7,2024-10-07,South,Clothing,NaN,2.0,38.0,Cash
7,8,2024-10-08,None,Books,340.0,3.0,52.0,None
8,9,2024-10-09,East,Electronics,2100.0,1.0,27.0,Credit Card
9,10,2024-10-10,West,None,780.0,5.0,41.0,UPI
10,11,2024-10-11,North,Home,560.0,3.0,33.0,Debit Card
11,12,2024-10-12,South,Clothing,NaN,2.0,NaN,Cash
12,13,2024-10-13,East,Books,420.0,NaN,48.0,Credit Card
13,14,2024-10-14,West,Electronics,1800.0,1.0,26.0,None
14,15,2024-10-15,North,Home,920.0,4.0,35.0,UPI
15,16,2024-10-16,None,Clothing,510.0,3.0,42.0,Cash
16,17,2024-10-17,East,Books,380.0,2.0,NaN,Debit Card
17,18,2024-10-18,West,Electronics,NaN,1.0,31.0,Credit Card
18,19,2024-10-19,North,Home,1100.0,NaN,39.0,UPI
19,20,2024-10-20,South,Clothing,640.0,4.0,44.0,None

# Task 2: Handle Missing Values

In [4]:
#Filling with mode in region and product_category
region_mode = df['region'].mode()[0]
product_category_mode = df['product_category'].mode()[0]
df['region'].value_counts()
df['product_category'].value_counts()
new_df = df.fillna({
    "region": region_mode,
    "product_category": product_category_mode
})
new_df

,transaction_id,date,region,product_category,sales_amount,quantity,customer_age,payment_method
0,1,2024-10-01,North,Electronics,1200.0,2.0,25.0,Credit Card
1,2,2024-10-02,South,Clothing,450.0,5.0,34.0,UPI
2,3,2024-10-03,East,Clothing,890.0,3.0,NaN,Cash
3,4,2024-10-04,West,Books,NaN,1.0,45.0,Debit Card
4,5,2024-10-05,North,Electronics,1500.0,NaN,29.0,Credit Card
5,6,2024-10-06,North,Home,670.0,4.0,NaN,UPI
6,7,2024-10-07,South,Clothing,NaN,2.0,38.0,Cash
7,8,2024-10-08,North,Books,340.0,3.0,52.0,None
8,9,2024-10-09,East,Electronics,2100.0,1.0,27.0,Credit Card
9,10,2024-10-10,West,Clothing,780.0,5.0,41.0,UPI
10,11,2024-10-11,North,Home,560.0,3.0,33.0,Debit Card
11,12,2024-10-12,South,Clothing,NaN,2.0,NaN,Cash
12,13,2024-10-13,East,Books,420.0,NaN,48.0,Credit Card
13,14,2024-10-14,West,Electronics,1800.0,1.0,26.0,None
14,15,2024-10-15,North,Home,920.0,4.0,35.0,UPI
15,16,2024-10-16,North,Clothing,510.0,3.0,42.0,Cash
16,17,2024-10-17,East,Books,380.0,2.0,NaN,Debit Card
17,18,2024-10-18,West,Electronics,NaN,1.0,31.0,Credit Card
18,19,2024-10-19,North,Home,1100.0,NaN,39.0,UPI
19,20,2024-10-20,South,Clothing,640.0,4.0,44.0,None

In [5]:
#Filling sales_amount with median
median_sales = df['sales_amount'].median()
new_df = new_df.fillna({
    "sales_amount": median_sales
})
new_df

,transaction_id,date,region,product_category,sales_amount,quantity,customer_age,payment_method
0,1,2024-10-01,North,Electronics,1200.0,2.0,25.0,Credit Card
1,2,2024-10-02,South,Clothing,450.0,5.0,34.0,UPI
2,3,2024-10-03,East,Clothing,890.0,3.0,NaN,Cash
3,4,2024-10-04,West,Books,725.0,1.0,45.0,Debit Card
4,5,2024-10-05,North,Electronics,1500.0,NaN,29.0,Credit Card
5,6,2024-10-06,North,Home,670.0,4.0,NaN,UPI
6,7,2024-10-07,South,Clothing,725.0,2.0,38.0,Cash
7,8,2024-10-08,North,Books,340.0,3.0,52.0,None
8,9,2024-10-09,East,Electronics,2100.0,1.0,27.0,Credit Card
9,10,2024-10-10,West,Clothing,780.0,5.0,41.0,UPI
10,11,2024-10-11,North,Home,560.0,3.0,33.0,Debit Card
11,12,2024-10-12,South,Clothing,725.0,2.0,NaN,Cash
12,13,2024-10-13,East,Books,420.0,NaN,48.0,Credit Card
13,14,2024-10-14,West,Electronics,1800.0,1.0,26.0,None
14,15,2024-10-15,North,Home,920.0,4.0,35.0,UPI
15,16,2024-10-16,North,Clothing,510.0,3.0,42.0,Cash
16,17,2024-10-17,East,Books,380.0,2.0,NaN,Debit Card
17,18,2024-10-18,West,Electronics,725.0,1.0,31.0,Credit Card
18,19,2024-10-19,North,Home,1100.0,NaN,39.0,UPI
19,20,2024-10-20,South,Clothing,640.0,4.0,44.0,None

In [6]:
#Filling Quantity using forword fill(ffill)
new_df['quantity'] = new_df['quantity'].ffill()
new_df

,transaction_id,date,region,product_category,sales_amount,quantity,customer_age,payment_method
0,1,2024-10-01,North,Electronics,1200.0,2.0,25.0,Credit Card
1,2,2024-10-02,South,Clothing,450.0,5.0,34.0,UPI
2,3,2024-10-03,East,Clothing,890.0,3.0,NaN,Cash
3,4,2024-10-04,West,Books,725.0,1.0,45.0,Debit Card
4,5,2024-10-05,North,Electronics,1500.0,1.0,29.0,Credit Card
5,6,2024-10-06,North,Home,670.0,4.0,NaN,UPI
6,7,2024-10-07,South,Clothing,725.0,2.0,38.0,Cash
7,8,2024-10-08,North,Books,340.0,3.0,52.0,None
8,9,2024-10-09,East,Electronics,2100.0,1.0,27.0,Credit Card
9,10,2024-10-10,West,Clothing,780.0,5.0,41.0,UPI
10,11,2024-10-11,North,Home,560.0,3.0,33.0,Debit Card
11,12,2024-10-12,South,Clothing,725.0,2.0,NaN,Cash
12,13,2024-10-13,East,Books,420.0,2.0,48.0,Credit Card
13,14,2024-10-14,West,Electronics,1800.0,1.0,26.0,None
14,15,2024-10-15,North,Home,920.0,4.0,35.0,UPI
15,16,2024-10-16,North,Clothing,510.0,3.0,42.0,Cash
16,17,2024-10-17,East,Books,380.0,2.0,NaN,Debit Card
17,18,2024-10-18,West,Electronics,725.0,1.0,31.0,Credit Card
18,19,2024-10-19,North,Home,1100.0,1.0,39.0,UPI
19,20,2024-10-20,South,Clothing,640.0,4.0,44.0,None

In [7]:
#Filling Customer age with mean
mean_age = new_df['customer_age'].mean().round(2)
new_df['customer_age'] = new_df['customer_age'].fillna(mean_age)
new_df

,transaction_id,date,region,product_category,sales_amount,quantity,customer_age,payment_method
0,1,2024-10-01,North,Electronics,1200.0,2.0,25.00,Credit Card
1,2,2024-10-02,South,Clothing,450.0,5.0,34.00,UPI
2,3,2024-10-03,East,Clothing,890.0,3.0,36.81,Cash
3,4,2024-10-04,West,Books,725.0,1.0,45.00,Debit Card
4,5,2024-10-05,North,Electronics,1500.0,1.0,29.00,Credit Card
5,6,2024-10-06,North,Home,670.0,4.0,36.81,UPI
6,7,2024-10-07,South,Clothing,725.0,2.0,38.00,Cash
7,8,2024-10-08,North,Books,340.0,3.0,52.00,None
8,9,2024-10-09,East,Electronics,2100.0,1.0,27.00,Credit Card
9,10,2024-10-10,West,Clothing,780.0,5.0,41.00,UPI
10,11,2024-10-11,North,Home,560.0,3.0,33.00,Debit Card
11,12,2024-10-12,South,Clothing,725.0,2.0,36.81,Cash
12,13,2024-10-13,East,Books,420.0,2.0,48.00,Credit Card
13,14,2024-10-14,West,Electronics,1800.0,1.0,26.00,None
14,15,2024-10-15,North,Home,920.0,4.0,35.00,UPI
15,16,2024-10-16,North,Clothing,510.0,3.0,42.00,Cash
16,17,2024-10-17,East,Books,380.0,2.0,36.81,Debit Card
17,18,2024-10-18,West,Electronics,725.0,1.0,31.00,Credit Card
18,19,2024-10-19,North,Home,1100.0,1.0,39.00,UPI
19,20,2024-10-20,South,Clothing,640.0,4.0,44.00,None

In [8]:
#Droping rows where payment_method has missing values
cleaned_df = new_df.dropna(subset=['payment_method'])
cleaned_df

,transaction_id,date,region,product_category,sales_amount,quantity,customer_age,payment_method
0,1,2024-10-01,North,Electronics,1200.0,2.0,25.00,Credit Card
1,2,2024-10-02,South,Clothing,450.0,5.0,34.00,UPI
2,3,2024-10-03,East,Clothing,890.0,3.0,36.81,Cash
3,4,2024-10-04,West,Books,725.0,1.0,45.00,Debit Card
4,5,2024-10-05,North,Electronics,1500.0,1.0,29.00,Credit Card
5,6,2024-10-06,North,Home,670.0,4.0,36.81,UPI
6,7,2024-10-07,South,Clothing,725.0,2.0,38.00,Cash
8,9,2024-10-09,East,Electronics,2100.0,1.0,27.00,Credit Card
9,10,2024-10-10,West,Clothing,780.0,5.0,41.00,UPI
10,11,2024-10-11,North,Home,560.0,3.0,33.00,Debit Card
11,12,2024-10-12,South,Clothing,725.0,2.0,36.81,Cash
12,13,2024-10-13,East,Books,420.0,2.0,48.00,Credit Card
14,15,2024-10-15,North,Home,920.0,4.0,35.00,UPI
15,16,2024-10-16,North,Clothing,510.0,3.0,42.00,Cash
16,17,2024-10-17,East,Books,380.0,2.0,36.81,Debit Card
17,18,2024-10-18,West,Electronics,725.0,1.0,31.00,Credit Card
18,19,2024-10-19,North,Home,1100.0,1.0,39.00,UPI

# Task 3: GroupBy Analysis

In [9]:
#Calculate total sales by region
cleaned_df.groupby('region')['sales_amount'].sum()

region
East     3790.0
North    6460.0
South    1900.0
West     2230.0
Name: sales_amount, dtype: float64

In [10]:
#Calculate average sales by product_category
cleaned_df.groupby('product_category')['sales_amount'].mean()

product_category
Books           508.333333
Clothing        680.000000
Electronics    1381.250000
Home            812.500000
Name: sales_amount, dtype: float64

In [11]:
# Group by both region and product_category, calculate total sales and quantity, then use reset_index() to flatten
cleaned_df.groupby(['region', 'product_category'])[['sales_amount','quantity']].sum().reset_index()

  region product_category  sales_amount  quantity
0   East            Books         800.0       4.0
1   East         Clothing         890.0       3.0
2   East      Electronics        2100.0       1.0
3  North         Clothing         510.0       3.0
4  North      Electronics        2700.0       3.0
5  North             Home        3250.0      12.0
6  South         Clothing        1900.0       9.0
7   West            Books         725.0       1.0
8   West         Clothing         780.0       5.0
9   West      Electronics         725.0       1.0

In [12]:
# Display top 3 region-product combinations by sales
cleaned_df.groupby(['region', 'product_category'])['sales_amount'].sum().nlargest(3)

region  product_category
North   Home                3250.0
        Electronics         2700.0
East    Electronics         2100.0
Name: sales_amount, dtype: float64

# Task 4: Custom Aggregation

In [21]:
#Create a function sales_range() that returns max - min of sales
def sales_range(x):
  return x.max() - x.min()

range = cleaned_df.groupby('region')['sales_amount'].agg([sales_range])
print(range)

        sales_range
region
East         1720.0
North         990.0
South         275.0
West           55.0

In [22]:
#Use .agg() to calculate multiple metrics by region
cleaned_df.groupby('region').agg({
    'sales_amount':['sum', 'mean', 'max'],
    'quantity': ['sum', 'min']
})

       sales_amount                     quantity
                sum        mean     max      sum  min
region
East         3790.0  947.500000  2100.0      8.0  1.0
North        6460.0  922.857143  1500.0     18.0  1.0
South        1900.0  633.333333   725.0      9.0  2.0
West         2230.0  743.333333   780.0      7.0  1.0